### ISSUE TITLE
Make `demo-dump-cbor` more generally useful

### ISSUE THREAD

**Issue by thoughtpolice** [well-typed/binary-serialise-cbor#84]
We've been using CBOR in our projects for some time with good success, but one thing @Oblosys noted is `demo-dump-cbor` could be much, much more generally useful for all kinds of stuff.

This is a meta-ticket to keep track of various improvements (notably the ones originally filed by @Oblosys):
- [ ] Allow demo-dump-cbor to parse files containing a sequence of cbor values (#78)
- [x] Add more output options for demo-dump-cbor (#77)
- [x] Don't require demo-dump-cbor input file to have a .cbor extension (#76) 
- [x] Rename executables demo-dump-cbor and demo-aeson (#75)

and more. Please submit useful suggestions here and we can divvy them off or discuss for now, but I did want a place to keep track of overall improvements.

**Comment by thoughtpolice** [comment]
Closing this, since most of these are fixed. We can fix #78 sometime later.
